spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trading-app
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: crypto-trading